
title: "Max Schoening"
tagline: ""
description: "Follow <a href=\"https://micro.blog/mschoening\">@mschoening on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/mschoening\">@mschoening on Micro.blog</a>."
baseurl: ""
url: "http://blog.max.wtf"
markdown: "kramdown"
username: "mschoening"
microblog_user: "mschoening"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Max Schoening"
name: "Max Schoening"
gravatar_hash: "3d8a5c469513de0c1c674e48ad2ba356"
avatar: "https://micro.blog/mschoening/avatar.jpg"
full_name: "Max Schoening"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Pacific-New"
site_id: "2294"
gems: ["jekyll-paginate"]
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Max Schoening"